evaluation:
  agent_params:
    agent_name: "FROSTBYTE_AI_DEV.AGENTS.ELT_ROUTER"
    agent_type: "CORTEX AGENT"
  source_metadata:
    type: "dataset"
    dataset_name: "FROSTBYTE_AI_DEV.EVAL.DS_ROUTER_EVAL_V2"

metrics:
  - "answer_correctness"
  - "logical_consistency"
